var path = require('path');

function ConditionalExternalPlugin() {}

var externals = {
  'jquery': ['jQuery']
}

ConditionalExternalPlugin.prototype.apply = function(compiler) {
  compiler.plugin("emit", function(compilation, callback) {
    compilation.plugin('seal', function(arg) {
      console.log("foo", compilation);
    });
    console.log("foo", compilation.modules[1]._source);


    callback();
    // nmf.plugin("after-resolve", function(data) {
    //     console.log(data);
    //     // data.loaders.unshift(path.join(__dirname, "postloader.js"));
    // });
  });
  // compiler.plugin('compile', function (compilation, params) {
  //   console.log(compilation);
  //   // // Explore each chunk (build output):
  //   // compilation.chunks.forEach(function(chunk) {
  //   //   // Explore each module within the chunk (built inputs):
  //   //   chunk.modules.forEach(function(module) {
  //   //     // Explore each source file path that was included into the module:
  //   //     module.fileDependencies.forEach(function(filepath) {
  //   //       // we've learned a lot about the source structure now...
  //   //       console.log(filepath);
  //   //     });
  //   //   });
  //   //
  //   //   // Explore each asset filename generated by the chunk:
  //   //   chunk.files.forEach(function(filename) {
  //   //     // Get the asset source for each file generated by the chunk:
  //   //     var source = compilation.assets[filename].source();
  //   //   });
  //   // });
  // });
};

module.exports = ConditionalExternalPlugin;
